export async function loadExperienceModules() {
  const [
    { default: gsap },
    { ScrollTrigger },
    { ScrollSmoother },
    { Flip },
    { Observer },
    { CustomEase },
    { SplitText },
    { createHeroTimeline },
    { createSectionTransitions },
    { createHeroProjectController },
    { createBackgroundSystem },
    { createThemeController },
    { createSplitTextReveal },
    { createHeroShaderLayer },
    { createHeroProjectFlip },
    { registerBrandEasing },
  ] = await Promise.all([
    import('gsap'),
    import('gsap/ScrollTrigger'),
    import('gsap/ScrollSmoother'),
    import('gsap/Flip'),
    import('gsap/Observer'),
    import('gsap/CustomEase'),
    import('gsap/SplitText'),
    import('../animations/heroTimeline'),
    import('../animations/sectionTransitions'),
    import('./createHeroProjectController'),
    import('../background/createBackgroundSystem'),
    import('./createThemeController'),
    import('../animations/splitTextReveal'),
    import('../webgl/createHeroShaderLayer'),
    import('../animations/heroProjectFlip'),
    import('../animations/brandEasing'),
  ])

  return {
    gsap,
    ScrollTrigger,
    ScrollSmoother,
    Flip,
    Observer,
    CustomEase,
    SplitText,
    createHeroTimeline,
    createSectionTransitions,
    createHeroProjectController,
    createBackgroundSystem,
    createThemeController,
    createSplitTextReveal,
    createHeroShaderLayer,
    createHeroProjectFlip,
    registerBrandEasing,
  }
}
